openapi: 3.0.3
info:
  title: Horoscope v2 graphql
  version: 1.0.0
servers:
  - url: https://indexer-v2.dev.aurascan.io
    description: Server for testnet network. Support chains of auratestnet, serenity, euphoria, xstaxy, nois and sei
  - url: https://horoscope.aura.network
    description: Server for main network. Only support chain of xstaxy
  - url: https://indexer-v2.staging.aurascan.io
    description: Server for testnet network. Support chains of euphoria and xstaxy
tags:
  - name: contract
paths:
  /api/v2/graphql:
    post:
      tags:
        - contract
      summary: Query code id
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/codeid'
            examples:
              xstaxy:
                summary: Query on Xstaxy chain
                value:
                  operationName: codeid
                  query: "query codeid($limit: Int = 10, $codeId: Int = null) { xstaxy { code(limit: $limit, where: {code_id: {_eq: $codeId}}) { code_id created_at creator data_hash instantiate_permission status store_hash store_height type updated_at } } }"
                  variables:
                    limit: 10
                    codeId: null
              auratestnet:
                summary: Query on Aura Testnet chain
                value:
                  operationName: codeid
                  query: "query codeid($limit: Int = 10, $codeId: Int = null) { auratestnet { code(limit: $limit, where: {code_id: {_eq: $codeId}}) { code_id created_at creator data_hash instantiate_permission status store_hash store_height type updated_at } } }"
                  variables:
                    limit: 10
                    codeId: null
              serenity:
                summary: Query on Serenity chain
                value:
                  operationName: codeid
                  query: "query codeid($limit: Int = 10, $codeId: Int = null) { serenity { code(limit: $limit, where: {code_id: {_eq: $codeId}}) { code_id created_at creator data_hash instantiate_permission status store_hash store_height type updated_at } } }"
                  variables:
                    limit: 10
                    codeId: null
              euphoria:
                summary: Query on Euphoria chain
                value:
                  operationName: codeid
                  query: "query codeid($limit: Int = 10, $codeId: Int = null) { euphoria { code(limit: $limit, where: {code_id: {_eq: $codeId}}) { code_id created_at creator data_hash instantiate_permission status store_hash store_height type updated_at } } }"
                  variables:
                    limit: 10
                    codeId: null
              nois:
                summary: Query on Nois chain
                value:
                  operationName: codeid
                  query: "query codeid($limit: Int = 10, $codeId: Int = null) { nois { code(limit: $limit, where: {code_id: {_eq: $codeId}}) { code_id created_at creator data_hash instantiate_permission status store_hash store_height type updated_at } } }"
                  variables:
                    limit: 10
                    codeId: null
              sei:
                summary: Query on Sei chain
                value:
                  operationName: codeid
                  query: "query codeid($limit: Int = 10, $codeId: Int = null) { sei { code(limit: $limit, where: {code_id: {_eq: $codeId}}) { code_id created_at creator data_hash instantiate_permission status store_hash store_height type updated_at } } }"
                  variables:
                    limit: 10
                    codeId: null
      responses:
        '200':
          description: Successful operation
components:
  schemas:
    codeid:
      type: object
      properties:
        operationName:
          type: string
          example: codeid
          description: query name
        query:
          type: string
          example: "query codeid($limit: Int = 10, $codeId: Int = null) { euphoria { code(limit: $limit, where: {code_id: {_eq: $codeId}}) { code_id created_at creator data_hash instantiate_permission status store_hash store_height type updated_at } } }"
          description: Graphql query
        variables:
          type: object
          description: Variable in query
          example:
            limit: 10
            codeId: null
            
            
            
                  
            
          
            
