openapi: 3.0.3
info:
  title: Horoscope v2 graphql
  version: 1.0.0
servers:
  - url: https://indexer-v2.dev.aurascan.io
    description: Server for testnet network. Support chains of auratestnet, serenity, euphoria, xstaxy, nois and sei
  - url: https://horoscope.aura.network
    description: Server for main network. Only support chain of xstaxy
  - url: https://indexer-v2.staging.aurascan.io
    description: Server for testnet network. Support chains of euphoria and xstaxy
tags:
  - name: cw20
paths:
  /api/v2/graphql:
    post:
      tags:
        - cw20
      summary: Query cw20 activity
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/cw20activity'
            examples:
              xstaxy:
                summary: Query on Xstaxy chain
                value:
                  operationName: cw20activity
                  query: "query cw20activity($limit: Int = 10, $contractAddress: String = null) { xstaxy { cw20_activity(where: {cw20_contract: {smart_contract: {address: {_eq: $contractAddress}}}}, limit: $limit) { action amount from height sender to smart_contract_event_id id } } }"
                  variables:
                    limit: 10
                    contractAddress: aura17k2jq9dhq4kqgrtdrzt2qs0zy45cw0lmp3tfxysp7cwh5nxfg24st7ndc8
              auratestnet:
                summary: Query on Aura Testnet chain
                value:
                  operationName: cw20activity
                  query: "query cw20activity($limit: Int = 10, $contractAddress: String = null) { auratestnet { cw20_activity(where: {cw20_contract: {smart_contract: {address: {_eq: $contractAddress}}}}, limit: $limit) { action amount from height sender to smart_contract_event_id id } } }"
                  variables:
                    limit: 10
                    contractAddress: aura17k2jq9dhq4kqgrtdrzt2qs0zy45cw0lmp3tfxysp7cwh5nxfg24st7ndc8
              serenity:
                summary: Query on Serenity chain
                value:
                  operationName: cw20activity
                  query: "query cw20activity($limit: Int = 10, $contractAddress: String = null) { serenity { cw20_activity(where: {cw20_contract: {smart_contract: {address: {_eq: $contractAddress}}}}, limit: $limit) { action amount from height sender to smart_contract_event_id id } } }"
                  variables:
                    limit: 10
                    contractAddress: aura17k2jq9dhq4kqgrtdrzt2qs0zy45cw0lmp3tfxysp7cwh5nxfg24st7ndc8
              euphoria:
                summary: Query on Euphoria chain
                value:
                  operationName: cw20activity
                  query: "query cw20activity($limit: Int = 10, $contractAddress: String = null) { euphoria { cw20_activity(where: {cw20_contract: {smart_contract: {address: {_eq: $contractAddress}}}}, limit: $limit) { action amount from height sender to smart_contract_event_id id } } }"
                  variables:
                    limit: 10
                    contractAddress: aura17k2jq9dhq4kqgrtdrzt2qs0zy45cw0lmp3tfxysp7cwh5nxfg24st7ndc8
              nois:
                summary: Query on Nois chain
                value:
                  operationName: cw20activity
                  query: "query cw20activity($limit: Int = 10, $contractAddress: String = null) { nois { cw20_activity(where: {cw20_contract: {smart_contract: {address: {_eq: $contractAddress}}}}, limit: $limit) { action amount from height sender to smart_contract_event_id id } } }"
                  variables:
                    limit: 10
                    contractAddress: aura17k2jq9dhq4kqgrtdrzt2qs0zy45cw0lmp3tfxysp7cwh5nxfg24st7ndc8
              sei:
                summary: Query on Sei chain
                value:
                  operationName: cw20activity
                  query: "query cw20activity($limit: Int = 10, $contractAddress: String = null) { sei { cw20_activity(where: {cw20_contract: {smart_contract: {address: {_eq: $contractAddress}}}}, limit: $limit) { action amount from height sender to smart_contract_event_id id } } }"
                  variables:
                    limit: 10
                    contractAddress: aura17k2jq9dhq4kqgrtdrzt2qs0zy45cw0lmp3tfxysp7cwh5nxfg24st7ndc8
      responses:
        '200':
          description: Successful operation
components:
  schemas:
    cw20activity:
      type: object
      properties:
        operationName:
          type: string
          example: cw20activity
          description: query name
        query:
          type: string
          example: "query cw20activity($limit: Int = 10, $contractAddress: String = null) { euphoria { cw20_activity(where: {cw20_contract: {smart_contract: {address: {_eq: $contractAddress}}}}, limit: $limit) { action amount from height sender to smart_contract_event_id id } } }"
          description: Graphql query
        variables:
          type: object
          description: Variable in query
          example:
            limit: 10
            contractAddress: aura17k2jq9dhq4kqgrtdrzt2qs0zy45cw0lmp3tfxysp7cwh5nxfg24st7ndc8
            
            
                  
            
          
            
